name: Ejecutar worker de horarios

on:
  schedule:
    - cron: "0 6 * * *"  # 🕕 Se ejecuta todos los días a las 6:00 UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar worker
        env:
          PHP_ENDPOINT: ${{ secrets.PHP_ENDPOINT }}
        run: |
          python ext-worker.py
